local function dir()
    local s = debug.getinfo(1, "S").source:sub(2)
    return s:match("^(.*[/\\])")
end
local fusion = assert(bmd.scriptapp("Fusion", "localhost"))
local temp = dofile(dir() .. "../../test_support/temp_comp.lua")
local comp = assert(temp.acquire(fusion))
_G.comp = comp
local keep = assert(comp:AddTool("Background", -8, 0))
keep:SetAttrs({ TOOLS_Name = "Background_UserOwned" })
dofile(dir() .. "../build_shot_config.lua")
local apply = dofile(dir() .. "../apply_shot_config.lua")
local config = assert(apply.find_config(comp))
local t = comp.CurrentTime or 0
local function set(id, value) config[id][t] = value end
set(apply.CONTROL.root, "_FOQN:")
local n, p = apply.target_controls("Loader", 1)
set(n, "L_Managed")
set(p, "{root}/FOQN_E06/BRUTOS/H264/FOQN_E06_0010.mov")
n, p = apply.target_controls("Saver", 1)
set(n, "S_Managed_WIP")
set(p, "{root}/FOQN_E06/WIP/FOQN_E06_0010_WIP_v001.mov")
n, p = apply.target_controls("Saver", 2)
set(n, "S_Managed_Clean")
set(p, "{root}/FOQN_E06/RENDERS/FOQN_E06_0010_GFX_v001.mov")
local rebuild = dofile(dir() .. "../rebuild_managed_pipeline.lua")
assert(rebuild.run(comp))
assert(comp:FindTool("Background_UserOwned") ~= nil, "untagged node was removed")
assert(comp:FindTool("L_InputPrep_1") ~= nil, "InputPrep missing")
assert(comp:FindTool("S_OutputPackager_1") ~= nil, "first OutputPackager missing")
assert(comp:FindTool("S_OutputPackager_2") ~= nil, "second OutputPackager missing")
assert(comp:FindTool("S_Managed_WIP") ~= nil, "WIP Saver missing")
assert(comp:FindTool("S_Managed_Clean") ~= nil, "clean Saver missing")
assert(rebuild.run(comp))
assert(comp:FindTool("Background_UserOwned") ~= nil, "untagged node was removed on rebuild")
print("SHOTCONFIG_REBUILD_MANAGED_PIPELINE_HOST_TEST_OK")
return comp
