local function dir()
    local s = debug.getinfo(1, "S").source:sub(2)
    return s:match("^(.*[/\\])")
end
local fusion = assert(bmd.scriptapp("Fusion", "localhost"))
local temp = dofile(dir() .. "../../test_support/temp_comp.lua")
local comp = assert(temp.acquire(fusion))
_G.comp = comp
local keep = assert(comp:AddTool("Background", -8, 0))
keep:SetAttrs({ TOOLS_Name = "Background_UserOwned" })
dofile(dir() .. "../build_shot_config.lua")
local apply = dofile(dir() .. "../apply_shot_config.lua")
local config = assert(apply.find_config(comp))
local t = comp.CurrentTime or 0
local function set(id, value) config[id][t] = value end
set(apply.CONTROL.root, "_FOQN:")
local n, p = apply.target_controls("Loader", 1)
set(n, "SourceA")
set(p, "{root}/FOQN_E06/BRUTOS/H264/FOQN_E06_0010.mov")
n, p = apply.target_controls("Saver", 1)
set(n, "WIP")
set(p, "{root}/FOQN_E06/WIP/FOQN_E06_0010_WIP_v001.mov")
n, p = apply.target_controls("Saver", 2)
set(n, "Clean")
set(p, "{root}/FOQN_E06/RENDERS/FOQN_E06_0010_GFX_v001.mov")
local rebuild = dofile(dir() .. "../rebuild_managed_pipeline.lua")
assert(rebuild.run(comp))
assert(comp:FindTool("Background_UserOwned") ~= nil, "untagged node was removed")
assert(comp:FindTool("L_SourceA") ~= nil, "InputPrep missing")
assert(comp:FindTool("S_Wip") ~= nil, "WIP OutputPackager missing")
assert(comp:FindTool("S_Clean") ~= nil, "clean OutputPackager missing")
assert(comp:FindTool("WIP") ~= nil, "WIP Saver missing")
assert(comp:FindTool("Clean") ~= nil, "clean Saver missing")
local clean_packager = assert(comp:FindTool("S_Clean"), "clean OutputPackager missing")
assert(clean_packager.OP_OutputColorSpace[t] ~= nil, "output color metadata missing")
assert(clean_packager.OP_OutputGamma[t] ~= nil, "output gamma metadata missing")
assert(clean_packager.OP_OutputFormat[t] == "Movie", "output format metadata missing")
assert(clean_packager.OP_Compression[t] == "ProRes 422 HQ", "compression metadata missing")
assert(rebuild.run(comp))
assert(comp:FindTool("Background_UserOwned") ~= nil, "untagged node was removed on rebuild")
print("SHOTCONFIG_REBUILD_MANAGED_PIPELINE_HOST_TEST_OK")
return comp
